version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8082}:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=${MONGO_URI}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.runCommand({ ping: 1 }).ok'" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  default:
    name: voice_shopping_network
    driver: bridge

volumes:
  mongo_data:
